### PR TITLE
UI Enhancement for a More Professional and Premium Design  Improved- hacktoberfest2024

### PR DESCRIPTION
**Pull request by harith-hacky03**

### CODE REVIEW

**Comment by TheOpenInnovator** [comment]
Hey @harith-hacky03 can you provide the screen shots of your implementation along with generating some colours, how it's being displayed.

**Comment by harith-hacky03** [comment]
Screenshot 2024-10-17 at 10 54 13 PM
Screenshot 2024-10-17 at 9 55 03 PM
Here are the screenshots

**Comment by TheOpenInnovator** [comment]
Congratulations @harith-hacky03 Your PR has been merged. Hope you curate more valuable issues and work on them.

**Comment by harith-hacky03** [comment]
Thank you so much!

**Pull request merged**
